# Generated by Django 3.2.9 on 2021-11-07 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20211107_0927'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='summary2',
            field=models.TextField(default=True),
            preserve_default=False,
        ),
    ]
