# Generated by Django 3.2.9 on 2021-11-13 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_summary2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='summary2',
        ),
        migrations.AddField(
            model_name='product',
            name='featured',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
